<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-PF03QUE" failures="1" tests="5" name="RetryMultiple" time="0.12" errors="0" timestamp="2022-05-03T08:55:11 IST">
  <testcase classname="com.testNG.RetryTest" name="method1" time="0.022">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase classname="com.testNG.RetryTest" name="method1" time="0.002">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase classname="com.testNG.RetryTest" name="method1" time="0.0">
    <skipped/>
  </testcase> <!-- method1 -->
  <testcase classname="com.testNG.RetryTest" name="method1" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testNG.RetryTest.method1(RetryTest.java:11)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- method1 -->
  <testcase classname="com.testNG.RetryTest" name="method2" time="0.002"/>
</testsuite> <!-- RetryMultiple -->
